version: '3.8'

services:
  ### ElasticSearch ######################################################################
  es01:
    build:
      context: ./elasticsearch
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${ELASTICSEARCH_PATH}/01/data:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_PATH}/01/plugins:/usr/share/elasticsearch/plugins
      - ${ELASTICSEARCH_LOG}/01:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      backend:
        ipv4_address: ${ES01_IP}

  es02:
    build:
      context: ./elasticsearch
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${ELASTICSEARCH_PATH}/02/data:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_PATH}/02/plugins:/usr/share/elasticsearch/plugins
      - ${ELASTICSEARCH_LOG}/02:/usr/share/elasticsearch/logs
    networks:
      backend:
        ipv4_address: ${ES02_IP}

  es03:
    build:
      context: ./elasticsearch
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${ELASTICSEARCH_PATH}/03/data:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_PATH}/03/plugins:/usr/share/elasticsearch/plugins
      - ${ELASTICSEARCH_LOG}/03:/usr/share/elasticsearch/logs
    networks:
      backend:
        ipv4_address: ${ES03_IP}

  ### kibana ############################################################################
  kibana:
    build:
      context: ./kibana
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - XPACK_MONITORING_ENABLED=true
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - I18N_LOCALE=zh-CN
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD="${ELASTICSEARCH_PASSWORD}"
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      backend:
        ipv4_address: ${KIBANA_IP}
networks:
  backend:
    external: true
